version: '2'
services:
    fpm:
        image: hw2-fpm
        container_name: hw2_fpm
        build:
            context: ../..
            dockerfile: ./docker/dev/fpm/Dockerfile
        restart: 'no'
        env_file: ./env.conf
        volumes:
            - ../../:/code
        entrypoint: /code/docker/dev/fpm/entrypoint.sh
        networks:
            - default
    nginx:
        image: boky/nginx:latest
        container_name: hw2_nginx
        ports:
            - 80:80
        depends_on:
            - fpm
        volumes_from:
            - fpm:ro
        volumes:
            - ../dev/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: 'no'
        networks:
            default:
                aliases:
                    - hw2.localhost
            proxy:
                aliases:
                    - hw2.localhost
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:hw2.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.docker.network=traefik_webgateway"
    db:
        container_name: hw2_db
        image: mariadb
        environment:
            - MYSQL_DATABASE=hw2
            - MYSQL_ROOT_PASSWORD=mypass
        volumes:
            - ./mysql/:/var/lib/mysql/
        restart: 'no'
        networks:
            - default

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        env_file:
            - './env.influxdb'
        volumes:
            # Data persistency
            # sudo mkdir -p /srv/docker/influxdb/data
            - ../dev/influxdb/data:/var/lib/influxdb
        networks:
            - default

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - ../dev/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        env_file:
            - './env.grafana'
        links:
            - influxdb
        volumes:
            # Data persistency
            # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
            - ../dev/grafana/data:/var/lib/grafana
        networks:
            - default

networks:
    webgateway:
        driver: bridge

    default:
        driver: bridge
    proxy:
        external:
            name: traefik_webgateway
